jluct_blog_homepage:
    path:     /{page}
    defaults: { _controller: JluctBlogBundle:Default:index, page: 1 }
    requirements:
        page: \d+

jluct_blog_post:
    path:     /post/{id}
    defaults: { _controller: JluctBlogBundle:Default:post}
    requirements:
        id: \d+

jluct_blog_registration:
    path:     /registration
    defaults: { _controller: JluctBlogBundle:Security:registration}

jluct_blog_login:
    path:     /login
    defaults: { _controller: JluctBlogBundle:Security:login}

jluct_blog_logout:
    path:     /logout

jluct_blog_check:
    path: /login_check

imports:
   resource: "admin/routing.yml"
   prefix:   /admin