jluct_blog_admin_post_view:
    path:     /post/{page}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:index, page: 1 }
    requirements:
        page: \d+

jluct_blog_admin_post_public:
    path:     /post/public/{id}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:public }
    requirements:
        id: \d+

jluct_blog_admin_post_create:
    path:     /post/create
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:create }

jluct_blog_admin_post_update:
    path:     /post/update/{id}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:update }
    requirements:
        id: \d+

jluct_blog_admin_post_delete:
    path:     /post/delete/{id}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:delete }
    requirements:
        id: \d+