jluct_blog_admin_post_view:
    path:     /post/{page}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:index, page: 1 }
    requirements:
        page: \d+

jluct_blog_admin_post_public:
    path:     /post/public/{id}
    defaults: { _controller: JluctBlogBundle:Admin/PostAdmin:public }
    requirements:
        id: \d+